services:
  bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    environment:
      - TELEGRAM_API_ID=202487
      - TELEGRAM_API_HASH=64a9c79af108ff27016cd442399fd860
      - TELEGRAM_LOCAL=true
    ports:
      - "8081:8081"
    volumes:
      - bot-api-data:/var/lib/telegram-bot-api
      - shared-tmp:/tmp/pornhub-bot
    restart: unless-stopped

  bot:
    build: .
    container_name: pornhub-bot
    env_file:
      - .env
    volumes:
      - pornhub-data:/app/data
      - shared-tmp:/tmp/pornhub-bot
    depends_on:
      - bot-api
    restart: unless-stopped

volumes:
  bot-api-data:
  pornhub-data:
  shared-tmp:
